name: CI

on
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Build and Test
      run: sbt -v +test
    - name: Run
      run: sbt run
